### ISSUE TITLE
Crash on 1.21

### ISSUE THREAD

**Issue by sternschnaube** [Tater-Certified/Potatoptimize#15]
https://pastebin.com/raw/qHt6FfBQ

**Comment by QPCrummer** [comment]
This version should fix this issue. Can you please test it to ensure this is true:
https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.2

**Comment by sternschnaube** [comment]
Thank you, I verify it later 😄

**Comment by ViTulyankin** [comment]
> This version should fix this issue. Can you please test it to ensure this is true

Still crashing. 
Tested with only FabricAPI and Lithium installed.

[Error Message.txt](https://github.com/user-attachments/files/15976215/Error.Message.txt)

**Comment by sternschnaube** [comment]
No crash anymore! Thanks.
